---
title: "Introduction"
tutorial:
  id: "37"
output:
  learnr::tutorial:
    progressive: true
    ace_theme: github 
    theme: united
runtime: shiny_prerendered
description: "This tutorial will introduce you to the basics of R."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(gradethis)
library(learnr)
library(learnrhash)
library(learncausalinfeRence)
tutorial_options(exercise.checker = gradethis::grade_learnr)
tut_reptitle <- "Introduction: Output Report"
```


## Basics of R

### R as a calculator


First, we'll learn how to use R as a calculator.

- Use the `+` sign to add 5 and 3

```{r add, exercise=TRUE}

```

```{r add-check}
grade_result(
  pass_if(~ identical(.result, 8))
)
```


- Use the `-` sign to subtract 3 from 5

```{r subtract, exercise=TRUE, exercise.lines = 5}

```

```{r subtract-check}
grade_result(
  pass_if(~ identical(.result, 2))
)
```

## Submit 

```{r context = "server"}
submission_server()
```

```{r context = "setup"}
submission_ui
```

